pt-BR:
  languageCode: pt-BR
  laguangeDirection: ltr
  languageName: Português
  weight: 1
  menu:
    main:
      - identifier: blog
        name: Blog
        pageRef: /posts
        weight: 10
      - identifier: about
        name: Sobre
        pageRef: /about
        weight: 20
      - identifier: github
        name: GitHub
        url: https://github.com/gianlcl/iglabs-blog
        weight: 30
en:
  languageCode: en-US
  laguangeDirection: ltr
  languageName: English
  weight: 2
  menu:
    main:
      - identifier: blog
        name: Blog
        pageRef: /posts
        weight: 10
      - identifier: about
        name: About
        pageRef: /about
        weight: 20
      - identifier: github
        name: GitHub
        url: https://github.com/gianlcl/iglabs-blog
        weight: 30
