contentTypeName: post
showAuthor: true
author:
  name: Gian Cavalcante
  email: gianlcl@iglabs.com.br
header:
  logo: logo.svg
footer:
  since: 2024
  poweredby: true
giscus:
  enabled: true
  repo: gianlcl/iglabs-blog
  repoId: R_kgDONX2mnA
  category: Announcements
  categoryId: DIC_kwDONX2mnM4Ck07O
  mapping: pathname
  strict: "0"
  reactionsEnabled: "1"
  emitMetadata: "0"
  inputPosition: top
  theme: preferred_color_scheme
  lang: pt
  loading: lazy
social_media:
  items:
    - enabled: true
      title: Github
      icon: brand-github
      link: https://github.com/gianlcl
    - enabled: true
      title: Linkedin
      icon: brand-linkedin
      link: https://www.linkedin.com/in/gian-cavalcante
    - enabled: true
      title: Bluesky
      icon: brand-bluesky
      link: https://bsky.app/profile/gianlcl.online
