giscus:
  enabled: true
  repo: gianlcl/iglabs-blog
  repoID: R_kgDONX2mnA
  category: Announcements
  categoryID: DIC_kwDONX2mnM4Ck07O
  mapping: pathname
  strict: "0"
  reactionsEnabled: "1"
  emitMetadata: "0"
  inputPosition: top
  theme: preferred_color_scheme
  lang: pt
  loading: lazy
  crossorigin: anonymous
